# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yidamsg/Yida_pose.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Yida_pose(genpy.Message):
  _md5sum = "1952e558db386574a9633d011a903b3d"
  _type = "yidamsg/Yida_pose"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 id
float64 x
float64 y
float64 z
float32 anglex
float32 angley
float32 anglez
float32 prob
float32 x1
float32 y1
float32 x2
float32 y2
float32 x3
float32 y3
float32 x4
float32 y4
int32 road_line_status
float32 robot_road_angle
float32 distance
float32 turn_angle

"""
  __slots__ = ['id','x','y','z','anglex','angley','anglez','prob','x1','y1','x2','y2','x3','y3','x4','y4','road_line_status','robot_road_angle','distance','turn_angle']
  _slot_types = ['int32','float64','float64','float64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','int32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,x,y,z,anglex,angley,anglez,prob,x1,y1,x2,y2,x3,y3,x4,y4,road_line_status,robot_road_angle,distance,turn_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Yida_pose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.anglex is None:
        self.anglex = 0.
      if self.angley is None:
        self.angley = 0.
      if self.anglez is None:
        self.anglez = 0.
      if self.prob is None:
        self.prob = 0.
      if self.x1 is None:
        self.x1 = 0.
      if self.y1 is None:
        self.y1 = 0.
      if self.x2 is None:
        self.x2 = 0.
      if self.y2 is None:
        self.y2 = 0.
      if self.x3 is None:
        self.x3 = 0.
      if self.y3 is None:
        self.y3 = 0.
      if self.x4 is None:
        self.x4 = 0.
      if self.y4 is None:
        self.y4 = 0.
      if self.road_line_status is None:
        self.road_line_status = 0
      if self.robot_road_angle is None:
        self.robot_road_angle = 0.
      if self.distance is None:
        self.distance = 0.
      if self.turn_angle is None:
        self.turn_angle = 0.
    else:
      self.id = 0
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.anglex = 0.
      self.angley = 0.
      self.anglez = 0.
      self.prob = 0.
      self.x1 = 0.
      self.y1 = 0.
      self.x2 = 0.
      self.y2 = 0.
      self.x3 = 0.
      self.y3 = 0.
      self.x4 = 0.
      self.y4 = 0.
      self.road_line_status = 0
      self.robot_road_angle = 0.
      self.distance = 0.
      self.turn_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i3d12fi3f().pack(_x.id, _x.x, _x.y, _x.z, _x.anglex, _x.angley, _x.anglez, _x.prob, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.road_line_status, _x.robot_road_angle, _x.distance, _x.turn_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 92
      (_x.id, _x.x, _x.y, _x.z, _x.anglex, _x.angley, _x.anglez, _x.prob, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.road_line_status, _x.robot_road_angle, _x.distance, _x.turn_angle,) = _get_struct_i3d12fi3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i3d12fi3f().pack(_x.id, _x.x, _x.y, _x.z, _x.anglex, _x.angley, _x.anglez, _x.prob, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.road_line_status, _x.robot_road_angle, _x.distance, _x.turn_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 92
      (_x.id, _x.x, _x.y, _x.z, _x.anglex, _x.angley, _x.anglez, _x.prob, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4, _x.road_line_status, _x.robot_road_angle, _x.distance, _x.turn_angle,) = _get_struct_i3d12fi3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i3d12fi3f = None
def _get_struct_i3d12fi3f():
    global _struct_i3d12fi3f
    if _struct_i3d12fi3f is None:
        _struct_i3d12fi3f = struct.Struct("<i3d12fi3f")
    return _struct_i3d12fi3f
