(cl:in-package yidamsg-srv)
(cl:export '(X1-VAL
          X1
          Y1-VAL
          Y1
          Z1-VAL
          Z1
          X2-VAL
          X2
          Y2-VAL
          Y2
          Z2-VAL
          Z2
          X3-VAL
          X3
          Y3-VAL
          Y3
          Z3-VAL
          Z3
          X4-VAL
          X4
          Y4-VAL
          Y4
          Z4-VAL
          Z4
          FLAG-VAL
          FLAG
          STATUS-VAL
          STATUS
))