# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yidamsg/OriginWeather.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class OriginWeather(genpy.Message):
  _md5sum = "f8f36e3f2096377d234886a58cfe782a"
  _type = "yidamsg/OriginWeather"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 pressure
int32 temperature
int32 humidity
int32 illumination
int32 windspeed
int32 winddirection
int32 rainorsnow
"""
  __slots__ = ['pressure','temperature','humidity','illumination','windspeed','winddirection','rainorsnow']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pressure,temperature,humidity,illumination,windspeed,winddirection,rainorsnow

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OriginWeather, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pressure is None:
        self.pressure = 0
      if self.temperature is None:
        self.temperature = 0
      if self.humidity is None:
        self.humidity = 0
      if self.illumination is None:
        self.illumination = 0
      if self.windspeed is None:
        self.windspeed = 0
      if self.winddirection is None:
        self.winddirection = 0
      if self.rainorsnow is None:
        self.rainorsnow = 0
    else:
      self.pressure = 0
      self.temperature = 0
      self.humidity = 0
      self.illumination = 0
      self.windspeed = 0
      self.winddirection = 0
      self.rainorsnow = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7i().pack(_x.pressure, _x.temperature, _x.humidity, _x.illumination, _x.windspeed, _x.winddirection, _x.rainorsnow))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.pressure, _x.temperature, _x.humidity, _x.illumination, _x.windspeed, _x.winddirection, _x.rainorsnow,) = _get_struct_7i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7i().pack(_x.pressure, _x.temperature, _x.humidity, _x.illumination, _x.windspeed, _x.winddirection, _x.rainorsnow))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.pressure, _x.temperature, _x.humidity, _x.illumination, _x.windspeed, _x.winddirection, _x.rainorsnow,) = _get_struct_7i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7i = None
def _get_struct_7i():
    global _struct_7i
    if _struct_7i is None:
        _struct_7i = struct.Struct("<7i")
    return _struct_7i
