// Generated by gencpp from file yidamsg/audio_broadcase.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_AUDIO_BROADCASE_H
#define YIDAMSG_MESSAGE_AUDIO_BROADCASE_H

#include <ros/service_traits.h>


#include <yidamsg/audio_broadcaseRequest.h>
#include <yidamsg/audio_broadcaseResponse.h>


namespace yidamsg
{

struct audio_broadcase
{

typedef audio_broadcaseRequest Request;
typedef audio_broadcaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct audio_broadcase
} // namespace yidamsg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yidamsg::audio_broadcase > {
  static const char* value()
  {
    return "d1516e71632b10007ec52702691b117f";
  }

  static const char* value(const ::yidamsg::audio_broadcase&) { return value(); }
};

template<>
struct DataType< ::yidamsg::audio_broadcase > {
  static const char* value()
  {
    return "yidamsg/audio_broadcase";
  }

  static const char* value(const ::yidamsg::audio_broadcase&) { return value(); }
};


// service_traits::MD5Sum< ::yidamsg::audio_broadcaseRequest> should match 
// service_traits::MD5Sum< ::yidamsg::audio_broadcase > 
template<>
struct MD5Sum< ::yidamsg::audio_broadcaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::audio_broadcaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::audio_broadcaseRequest> should match 
// service_traits::DataType< ::yidamsg::audio_broadcase > 
template<>
struct DataType< ::yidamsg::audio_broadcaseRequest>
{
  static const char* value()
  {
    return DataType< ::yidamsg::audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::audio_broadcaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yidamsg::audio_broadcaseResponse> should match 
// service_traits::MD5Sum< ::yidamsg::audio_broadcase > 
template<>
struct MD5Sum< ::yidamsg::audio_broadcaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::audio_broadcaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::audio_broadcaseResponse> should match 
// service_traits::DataType< ::yidamsg::audio_broadcase > 
template<>
struct DataType< ::yidamsg::audio_broadcaseResponse>
{
  static const char* value()
  {
    return DataType< ::yidamsg::audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::audio_broadcaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YIDAMSG_MESSAGE_AUDIO_BROADCASE_H
