// Generated by gencpp from file yidamsg/battery.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_BATTERY_H
#define YIDAMSG_MESSAGE_BATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct battery_
{
  typedef battery_<ContainerAllocator> Type;

  battery_()
    : charge(0.0)  {
    }
  battery_(const ContainerAllocator& _alloc)
    : charge(0.0)  {
  (void)_alloc;
    }



   typedef float _charge_type;
  _charge_type charge;





  typedef boost::shared_ptr< ::yidamsg::battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::battery_<ContainerAllocator> const> ConstPtr;

}; // struct battery_

typedef ::yidamsg::battery_<std::allocator<void> > battery;

typedef boost::shared_ptr< ::yidamsg::battery > batteryPtr;
typedef boost::shared_ptr< ::yidamsg::battery const> batteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::battery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::battery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::battery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::battery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::battery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::battery_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f43634fd818f1f0b26dc3c72b9bab8a8";
  }

  static const char* value(const ::yidamsg::battery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf43634fd818f1f0bULL;
  static const uint64_t static_value2 = 0x26dc3c72b9bab8a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/battery";
  }

  static const char* value(const ::yidamsg::battery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::battery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 charge\n\
";
  }

  static const char* value(const ::yidamsg::battery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::battery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.charge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct battery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::battery_<ContainerAllocator>& v)
  {
    s << indent << "charge: ";
    Printer<float>::stream(s, indent + "  ", v.charge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_BATTERY_H
