// Generated by gencpp from file yidamsg/CameraControlRequest.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_CAMERACONTROLREQUEST_H
#define YIDAMSG_MESSAGE_CAMERACONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct CameraControlRequest_
{
  typedef CameraControlRequest_<ContainerAllocator> Type;

  CameraControlRequest_()
    : angle1(0.0)
    , angle2(0.0)  {
    }
  CameraControlRequest_(const ContainerAllocator& _alloc)
    : angle1(0.0)
    , angle2(0.0)  {
  (void)_alloc;
    }



   typedef float _angle1_type;
  _angle1_type angle1;

   typedef float _angle2_type;
  _angle2_type angle2;





  typedef boost::shared_ptr< ::yidamsg::CameraControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::CameraControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraControlRequest_

typedef ::yidamsg::CameraControlRequest_<std::allocator<void> > CameraControlRequest;

typedef boost::shared_ptr< ::yidamsg::CameraControlRequest > CameraControlRequestPtr;
typedef boost::shared_ptr< ::yidamsg::CameraControlRequest const> CameraControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::CameraControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::CameraControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::CameraControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::CameraControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::CameraControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "343bc431207c2d7a78fcf1a862aeef25";
  }

  static const char* value(const ::yidamsg::CameraControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x343bc431207c2d7aULL;
  static const uint64_t static_value2 = 0x78fcf1a862aeef25ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/CameraControlRequest";
  }

  static const char* value(const ::yidamsg::CameraControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle1\n\
float32 angle2\n\
";
  }

  static const char* value(const ::yidamsg::CameraControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle1);
      stream.next(m.angle2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::CameraControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::CameraControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle1: ";
    Printer<float>::stream(s, indent + "  ", v.angle1);
    s << indent << "angle2: ";
    Printer<float>::stream(s, indent + "  ", v.angle2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_CAMERACONTROLREQUEST_H
