// Generated by gencpp from file yidamsg/car_status.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_CAR_STATUS_H
#define YIDAMSG_MESSAGE_CAR_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct car_status_
{
  typedef car_status_<ContainerAllocator> Type;

  car_status_()
    : name()
    , left_data()
    , right_data()  {
    }
  car_status_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , left_data(_alloc)
    , right_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _left_data_type;
  _left_data_type left_data;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _right_data_type;
  _right_data_type right_data;





  typedef boost::shared_ptr< ::yidamsg::car_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::car_status_<ContainerAllocator> const> ConstPtr;

}; // struct car_status_

typedef ::yidamsg::car_status_<std::allocator<void> > car_status;

typedef boost::shared_ptr< ::yidamsg::car_status > car_statusPtr;
typedef boost::shared_ptr< ::yidamsg::car_status const> car_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::car_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::car_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::car_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::car_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::car_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::car_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::car_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::car_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::car_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0fdc85453ace119bca6040d3b417a15";
  }

  static const char* value(const ::yidamsg::car_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0fdc85453ace119ULL;
  static const uint64_t static_value2 = 0xbca6040d3b417a15ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::car_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/car_status";
  }

  static const char* value(const ::yidamsg::car_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::car_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float32[] left_data\n\
float32[] right_data\n\
";
  }

  static const char* value(const ::yidamsg::car_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::car_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.left_data);
      stream.next(m.right_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct car_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::car_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::car_status_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "left_data[]" << std::endl;
    for (size_t i = 0; i < v.left_data.size(); ++i)
    {
      s << indent << "  left_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.left_data[i]);
    }
    s << indent << "right_data[]" << std::endl;
    for (size_t i = 0; i < v.right_data.size(); ++i)
    {
      s << indent << "  right_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.right_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_CAR_STATUS_H
