// Generated by gencpp from file yidamsg/ControlMode.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_CONTROLMODE_H
#define YIDAMSG_MESSAGE_CONTROLMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct ControlMode_
{
  typedef ControlMode_<ContainerAllocator> Type;

  ControlMode_()
    : robot_id(0)
    , mode(0)  {
    }
  ControlMode_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;

   typedef int32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::yidamsg::ControlMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::ControlMode_<ContainerAllocator> const> ConstPtr;

}; // struct ControlMode_

typedef ::yidamsg::ControlMode_<std::allocator<void> > ControlMode;

typedef boost::shared_ptr< ::yidamsg::ControlMode > ControlModePtr;
typedef boost::shared_ptr< ::yidamsg::ControlMode const> ControlModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::ControlMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::ControlMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::ControlMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::ControlMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::ControlMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::ControlMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::ControlMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::ControlMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::ControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c61e1d7d4546c212fbed829203d7559d";
  }

  static const char* value(const ::yidamsg::ControlMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc61e1d7d4546c212ULL;
  static const uint64_t static_value2 = 0xfbed829203d7559dULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::ControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/ControlMode";
  }

  static const char* value(const ::yidamsg::ControlMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::ControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot_id\n\
int32 mode\n\
";
  }

  static const char* value(const ::yidamsg::ControlMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::ControlMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::ControlMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::ControlMode_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_CONTROLMODE_H
