// Generated by gencpp from file yidamsg/ControlDoor.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_CONTROLDOOR_H
#define YIDAMSG_MESSAGE_CONTROLDOOR_H

#include <ros/service_traits.h>


#include <yidamsg/ControlDoorRequest.h>
#include <yidamsg/ControlDoorResponse.h>


namespace yidamsg
{

struct ControlDoor
{

typedef ControlDoorRequest Request;
typedef ControlDoorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlDoor
} // namespace yidamsg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yidamsg::ControlDoor > {
  static const char* value()
  {
    return "a0a40dfc84ba309f827118ccd5e5ca07";
  }

  static const char* value(const ::yidamsg::ControlDoor&) { return value(); }
};

template<>
struct DataType< ::yidamsg::ControlDoor > {
  static const char* value()
  {
    return "yidamsg/ControlDoor";
  }

  static const char* value(const ::yidamsg::ControlDoor&) { return value(); }
};


// service_traits::MD5Sum< ::yidamsg::ControlDoorRequest> should match 
// service_traits::MD5Sum< ::yidamsg::ControlDoor > 
template<>
struct MD5Sum< ::yidamsg::ControlDoorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::ControlDoor >::value();
  }
  static const char* value(const ::yidamsg::ControlDoorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::ControlDoorRequest> should match 
// service_traits::DataType< ::yidamsg::ControlDoor > 
template<>
struct DataType< ::yidamsg::ControlDoorRequest>
{
  static const char* value()
  {
    return DataType< ::yidamsg::ControlDoor >::value();
  }
  static const char* value(const ::yidamsg::ControlDoorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yidamsg::ControlDoorResponse> should match 
// service_traits::MD5Sum< ::yidamsg::ControlDoor > 
template<>
struct MD5Sum< ::yidamsg::ControlDoorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::ControlDoor >::value();
  }
  static const char* value(const ::yidamsg::ControlDoorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::ControlDoorResponse> should match 
// service_traits::DataType< ::yidamsg::ControlDoor > 
template<>
struct DataType< ::yidamsg::ControlDoorResponse>
{
  static const char* value()
  {
    return DataType< ::yidamsg::ControlDoor >::value();
  }
  static const char* value(const ::yidamsg::ControlDoorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YIDAMSG_MESSAGE_CONTROLDOOR_H
