// Generated by gencpp from file yidamsg/fly_ctl.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_FLY_CTL_H
#define YIDAMSG_MESSAGE_FLY_CTL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct fly_ctl_
{
  typedef fly_ctl_<ContainerAllocator> Type;

  fly_ctl_()
    : channel(0)
    , data(0)  {
    }
  fly_ctl_(const ContainerAllocator& _alloc)
    : channel(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef int16_t _channel_type;
  _channel_type channel;

   typedef int16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::yidamsg::fly_ctl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::fly_ctl_<ContainerAllocator> const> ConstPtr;

}; // struct fly_ctl_

typedef ::yidamsg::fly_ctl_<std::allocator<void> > fly_ctl;

typedef boost::shared_ptr< ::yidamsg::fly_ctl > fly_ctlPtr;
typedef boost::shared_ptr< ::yidamsg::fly_ctl const> fly_ctlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::fly_ctl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::fly_ctl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::fly_ctl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::fly_ctl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::fly_ctl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::fly_ctl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::fly_ctl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::fly_ctl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::fly_ctl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d986998f9a980ae4301ea3b5442b289";
  }

  static const char* value(const ::yidamsg::fly_ctl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d986998f9a980aeULL;
  static const uint64_t static_value2 = 0x4301ea3b5442b289ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::fly_ctl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/fly_ctl";
  }

  static const char* value(const ::yidamsg::fly_ctl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::fly_ctl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 channel\n\
int16 data\n\
";
  }

  static const char* value(const ::yidamsg::fly_ctl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::fly_ctl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fly_ctl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::fly_ctl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::fly_ctl_<ContainerAllocator>& v)
  {
    s << indent << "channel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.channel);
    s << indent << "data: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_FLY_CTL_H
