// Generated by gencpp from file yidamsg/GetBattery.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_GETBATTERY_H
#define YIDAMSG_MESSAGE_GETBATTERY_H

#include <ros/service_traits.h>


#include <yidamsg/GetBatteryRequest.h>
#include <yidamsg/GetBatteryResponse.h>


namespace yidamsg
{

struct GetBattery
{

typedef GetBatteryRequest Request;
typedef GetBatteryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBattery
} // namespace yidamsg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yidamsg::GetBattery > {
  static const char* value()
  {
    return "295e87f732e03ed6443766199f72b602";
  }

  static const char* value(const ::yidamsg::GetBattery&) { return value(); }
};

template<>
struct DataType< ::yidamsg::GetBattery > {
  static const char* value()
  {
    return "yidamsg/GetBattery";
  }

  static const char* value(const ::yidamsg::GetBattery&) { return value(); }
};


// service_traits::MD5Sum< ::yidamsg::GetBatteryRequest> should match 
// service_traits::MD5Sum< ::yidamsg::GetBattery > 
template<>
struct MD5Sum< ::yidamsg::GetBatteryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::GetBattery >::value();
  }
  static const char* value(const ::yidamsg::GetBatteryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::GetBatteryRequest> should match 
// service_traits::DataType< ::yidamsg::GetBattery > 
template<>
struct DataType< ::yidamsg::GetBatteryRequest>
{
  static const char* value()
  {
    return DataType< ::yidamsg::GetBattery >::value();
  }
  static const char* value(const ::yidamsg::GetBatteryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yidamsg::GetBatteryResponse> should match 
// service_traits::MD5Sum< ::yidamsg::GetBattery > 
template<>
struct MD5Sum< ::yidamsg::GetBatteryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::GetBattery >::value();
  }
  static const char* value(const ::yidamsg::GetBatteryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::GetBatteryResponse> should match 
// service_traits::DataType< ::yidamsg::GetBattery > 
template<>
struct DataType< ::yidamsg::GetBatteryResponse>
{
  static const char* value()
  {
    return DataType< ::yidamsg::GetBattery >::value();
  }
  static const char* value(const ::yidamsg::GetBatteryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YIDAMSG_MESSAGE_GETBATTERY_H
