// Generated by gencpp from file yidamsg/home.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_HOME_H
#define YIDAMSG_MESSAGE_HOME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct home_
{
  typedef home_<ContainerAllocator> Type;

  home_()
    : order()  {
    }
  home_(const ContainerAllocator& _alloc)
    : order(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _order_type;
  _order_type order;





  typedef boost::shared_ptr< ::yidamsg::home_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::home_<ContainerAllocator> const> ConstPtr;

}; // struct home_

typedef ::yidamsg::home_<std::allocator<void> > home;

typedef boost::shared_ptr< ::yidamsg::home > homePtr;
typedef boost::shared_ptr< ::yidamsg::home const> homeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::home_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::home_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::home_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::home_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::home_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::home_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::home_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::home_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::home_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9db207449ae86824d9e60bd906ef30e7";
  }

  static const char* value(const ::yidamsg::home_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9db207449ae86824ULL;
  static const uint64_t static_value2 = 0xd9e60bd906ef30e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::home_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/home";
  }

  static const char* value(const ::yidamsg::home_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::home_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string order\n\
";
  }

  static const char* value(const ::yidamsg::home_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::home_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct home_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::home_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::home_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_HOME_H
