// Generated by gencpp from file yidamsg/isInAutoChargerResponse.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_ISINAUTOCHARGERRESPONSE_H
#define YIDAMSG_MESSAGE_ISINAUTOCHARGERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct isInAutoChargerResponse_
{
  typedef isInAutoChargerResponse_<ContainerAllocator> Type;

  isInAutoChargerResponse_()
    : isCharging(0)  {
    }
  isInAutoChargerResponse_(const ContainerAllocator& _alloc)
    : isCharging(0)  {
  (void)_alloc;
    }



   typedef int32_t _isCharging_type;
  _isCharging_type isCharging;





  typedef boost::shared_ptr< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct isInAutoChargerResponse_

typedef ::yidamsg::isInAutoChargerResponse_<std::allocator<void> > isInAutoChargerResponse;

typedef boost::shared_ptr< ::yidamsg::isInAutoChargerResponse > isInAutoChargerResponsePtr;
typedef boost::shared_ptr< ::yidamsg::isInAutoChargerResponse const> isInAutoChargerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aec8fd091cfc40eae9abfae81e035982";
  }

  static const char* value(const ::yidamsg::isInAutoChargerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaec8fd091cfc40eaULL;
  static const uint64_t static_value2 = 0xe9abfae81e035982ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/isInAutoChargerResponse";
  }

  static const char* value(const ::yidamsg::isInAutoChargerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 isCharging\n\
\n\
";
  }

  static const char* value(const ::yidamsg::isInAutoChargerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isCharging);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct isInAutoChargerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::isInAutoChargerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::isInAutoChargerResponse_<ContainerAllocator>& v)
  {
    s << indent << "isCharging: ";
    Printer<int32_t>::stream(s, indent + "  ", v.isCharging);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_ISINAUTOCHARGERRESPONSE_H
