// Generated by gencpp from file yidamsg/MonitorPoint.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_MONITORPOINT_H
#define YIDAMSG_MESSAGE_MONITORPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct MonitorPoint_
{
  typedef MonitorPoint_<ContainerAllocator> Type;

  MonitorPoint_()
    : x1(0.0)
    , y1(0.0)
    , z1(0.0)
    , id(0)
    , log()  {
    }
  MonitorPoint_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , z1(0.0)
    , id(0)
    , log(_alloc)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _z1_type;
  _z1_type z1;

   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _log_type;
  _log_type log;





  typedef boost::shared_ptr< ::yidamsg::MonitorPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::MonitorPoint_<ContainerAllocator> const> ConstPtr;

}; // struct MonitorPoint_

typedef ::yidamsg::MonitorPoint_<std::allocator<void> > MonitorPoint;

typedef boost::shared_ptr< ::yidamsg::MonitorPoint > MonitorPointPtr;
typedef boost::shared_ptr< ::yidamsg::MonitorPoint const> MonitorPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::MonitorPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::MonitorPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::MonitorPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::MonitorPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::MonitorPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::MonitorPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::MonitorPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::MonitorPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::MonitorPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "255918c35eeec97106cb711f1f9fd76e";
  }

  static const char* value(const ::yidamsg::MonitorPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x255918c35eeec971ULL;
  static const uint64_t static_value2 = 0x06cb711f1f9fd76eULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::MonitorPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/MonitorPoint";
  }

  static const char* value(const ::yidamsg::MonitorPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::MonitorPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x1\n\
float32 y1\n\
float32 z1\n\
int32 id\n\
string log\n\
";
  }

  static const char* value(const ::yidamsg::MonitorPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::MonitorPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.z1);
      stream.next(m.id);
      stream.next(m.log);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MonitorPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::MonitorPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::MonitorPoint_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    s << indent << "z1: ";
    Printer<float>::stream(s, indent + "  ", v.z1);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "log: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.log);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_MONITORPOINT_H
