// Generated by gencpp from file yidamsg/OriginWeather.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_ORIGINWEATHER_H
#define YIDAMSG_MESSAGE_ORIGINWEATHER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct OriginWeather_
{
  typedef OriginWeather_<ContainerAllocator> Type;

  OriginWeather_()
    : pressure(0)
    , temperature(0)
    , humidity(0)
    , illumination(0)
    , windspeed(0)
    , winddirection(0)
    , rainorsnow(0)  {
    }
  OriginWeather_(const ContainerAllocator& _alloc)
    : pressure(0)
    , temperature(0)
    , humidity(0)
    , illumination(0)
    , windspeed(0)
    , winddirection(0)
    , rainorsnow(0)  {
  (void)_alloc;
    }



   typedef int32_t _pressure_type;
  _pressure_type pressure;

   typedef int32_t _temperature_type;
  _temperature_type temperature;

   typedef int32_t _humidity_type;
  _humidity_type humidity;

   typedef int32_t _illumination_type;
  _illumination_type illumination;

   typedef int32_t _windspeed_type;
  _windspeed_type windspeed;

   typedef int32_t _winddirection_type;
  _winddirection_type winddirection;

   typedef int32_t _rainorsnow_type;
  _rainorsnow_type rainorsnow;





  typedef boost::shared_ptr< ::yidamsg::OriginWeather_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::OriginWeather_<ContainerAllocator> const> ConstPtr;

}; // struct OriginWeather_

typedef ::yidamsg::OriginWeather_<std::allocator<void> > OriginWeather;

typedef boost::shared_ptr< ::yidamsg::OriginWeather > OriginWeatherPtr;
typedef boost::shared_ptr< ::yidamsg::OriginWeather const> OriginWeatherConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::OriginWeather_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::OriginWeather_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::OriginWeather_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::OriginWeather_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::OriginWeather_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::OriginWeather_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::OriginWeather_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::OriginWeather_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::OriginWeather_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8f36e3f2096377d234886a58cfe782a";
  }

  static const char* value(const ::yidamsg::OriginWeather_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8f36e3f2096377dULL;
  static const uint64_t static_value2 = 0x234886a58cfe782aULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::OriginWeather_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/OriginWeather";
  }

  static const char* value(const ::yidamsg::OriginWeather_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::OriginWeather_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pressure\n\
int32 temperature\n\
int32 humidity\n\
int32 illumination\n\
int32 windspeed\n\
int32 winddirection\n\
int32 rainorsnow\n\
";
  }

  static const char* value(const ::yidamsg::OriginWeather_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::OriginWeather_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pressure);
      stream.next(m.temperature);
      stream.next(m.humidity);
      stream.next(m.illumination);
      stream.next(m.windspeed);
      stream.next(m.winddirection);
      stream.next(m.rainorsnow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OriginWeather_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::OriginWeather_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::OriginWeather_<ContainerAllocator>& v)
  {
    s << indent << "pressure: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pressure);
    s << indent << "temperature: ";
    Printer<int32_t>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.humidity);
    s << indent << "illumination: ";
    Printer<int32_t>::stream(s, indent + "  ", v.illumination);
    s << indent << "windspeed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.windspeed);
    s << indent << "winddirection: ";
    Printer<int32_t>::stream(s, indent + "  ", v.winddirection);
    s << indent << "rainorsnow: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rainorsnow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_ORIGINWEATHER_H
