// Generated by gencpp from file yidamsg/OutHouseResponse.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_OUTHOUSERESPONSE_H
#define YIDAMSG_MESSAGE_OUTHOUSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct OutHouseResponse_
{
  typedef OutHouseResponse_<ContainerAllocator> Type;

  OutHouseResponse_()
    : isdone(false)  {
    }
  OutHouseResponse_(const ContainerAllocator& _alloc)
    : isdone(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isdone_type;
  _isdone_type isdone;





  typedef boost::shared_ptr< ::yidamsg::OutHouseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::OutHouseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OutHouseResponse_

typedef ::yidamsg::OutHouseResponse_<std::allocator<void> > OutHouseResponse;

typedef boost::shared_ptr< ::yidamsg::OutHouseResponse > OutHouseResponsePtr;
typedef boost::shared_ptr< ::yidamsg::OutHouseResponse const> OutHouseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::OutHouseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::OutHouseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::OutHouseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::OutHouseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::OutHouseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "155f126039916cf5358a013a0efc2beb";
  }

  static const char* value(const ::yidamsg::OutHouseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x155f126039916cf5ULL;
  static const uint64_t static_value2 = 0x358a013a0efc2bebULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/OutHouseResponse";
  }

  static const char* value(const ::yidamsg::OutHouseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isdone\n\
\n\
\n\
";
  }

  static const char* value(const ::yidamsg::OutHouseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isdone);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OutHouseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::OutHouseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::OutHouseResponse_<ContainerAllocator>& v)
  {
    s << indent << "isdone: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isdone);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_OUTHOUSERESPONSE_H
