// Generated by gencpp from file yidamsg/play_audioResponse.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_PLAY_AUDIORESPONSE_H
#define YIDAMSG_MESSAGE_PLAY_AUDIORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct play_audioResponse_
{
  typedef play_audioResponse_<ContainerAllocator> Type;

  play_audioResponse_()
    : message()
    , status(0)  {
    }
  play_audioResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , status(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::yidamsg::play_audioResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::play_audioResponse_<ContainerAllocator> const> ConstPtr;

}; // struct play_audioResponse_

typedef ::yidamsg::play_audioResponse_<std::allocator<void> > play_audioResponse;

typedef boost::shared_ptr< ::yidamsg::play_audioResponse > play_audioResponsePtr;
typedef boost::shared_ptr< ::yidamsg::play_audioResponse const> play_audioResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::play_audioResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::play_audioResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'yidamsg': ['/home/test/catkin_ws_dev/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::play_audioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::play_audioResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::play_audioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::play_audioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::play_audioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::play_audioResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::play_audioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fc2716b6a54000ffececb9430b5e899";
  }

  static const char* value(const ::yidamsg::play_audioResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fc2716b6a54000fULL;
  static const uint64_t static_value2 = 0xfececb9430b5e899ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::play_audioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/play_audioResponse";
  }

  static const char* value(const ::yidamsg::play_audioResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::play_audioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n\
int8 status\n\
\n\
";
  }

  static const char* value(const ::yidamsg::play_audioResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::play_audioResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct play_audioResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::play_audioResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::play_audioResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_PLAY_AUDIORESPONSE_H
