// Generated by gencpp from file yidamsg/play_audioRequest.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_PLAY_AUDIOREQUEST_H
#define YIDAMSG_MESSAGE_PLAY_AUDIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct play_audioRequest_
{
  typedef play_audioRequest_<ContainerAllocator> Type;

  play_audioRequest_()
    : file_path()
    , file_type(0)
    , audio_file_id(0)  {
    }
  play_audioRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)
    , file_type(0)
    , audio_file_id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_path_type;
  _file_path_type file_path;

   typedef int32_t _file_type_type;
  _file_type_type file_type;

   typedef int32_t _audio_file_id_type;
  _audio_file_id_type audio_file_id;





  typedef boost::shared_ptr< ::yidamsg::play_audioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::play_audioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct play_audioRequest_

typedef ::yidamsg::play_audioRequest_<std::allocator<void> > play_audioRequest;

typedef boost::shared_ptr< ::yidamsg::play_audioRequest > play_audioRequestPtr;
typedef boost::shared_ptr< ::yidamsg::play_audioRequest const> play_audioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::play_audioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::play_audioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'yidamsg': ['/home/test/catkin_ws_dev/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::play_audioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::play_audioRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::play_audioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::play_audioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::play_audioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::play_audioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::play_audioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "332ce3a2c780b6dcdb3659766440d67e";
  }

  static const char* value(const ::yidamsg::play_audioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x332ce3a2c780b6dcULL;
  static const uint64_t static_value2 = 0xdb3659766440d67eULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::play_audioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/play_audioRequest";
  }

  static const char* value(const ::yidamsg::play_audioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::play_audioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n\
int32 file_type\n\
int32 audio_file_id\n\
";
  }

  static const char* value(const ::yidamsg::play_audioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::play_audioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
      stream.next(m.file_type);
      stream.next(m.audio_file_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct play_audioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::play_audioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::play_audioRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file_path);
    s << indent << "file_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.file_type);
    s << indent << "audio_file_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.audio_file_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_PLAY_AUDIOREQUEST_H
