// Generated by gencpp from file yidamsg/Roi_cam.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_ROI_CAM_H
#define YIDAMSG_MESSAGE_ROI_CAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct Roi_cam_
{
  typedef Roi_cam_<ContainerAllocator> Type;

  Roi_cam_()
    : begin_x()
    , begin_y()
    , end_x()
    , end_y()
    , task_flag()  {
    }
  Roi_cam_(const ContainerAllocator& _alloc)
    : begin_x(_alloc)
    , begin_y(_alloc)
    , end_x(_alloc)
    , end_y(_alloc)
    , task_flag(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _begin_x_type;
  _begin_x_type begin_x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _begin_y_type;
  _begin_y_type begin_y;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _end_x_type;
  _end_x_type end_x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _end_y_type;
  _end_y_type end_y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_flag_type;
  _task_flag_type task_flag;





  typedef boost::shared_ptr< ::yidamsg::Roi_cam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::Roi_cam_<ContainerAllocator> const> ConstPtr;

}; // struct Roi_cam_

typedef ::yidamsg::Roi_cam_<std::allocator<void> > Roi_cam;

typedef boost::shared_ptr< ::yidamsg::Roi_cam > Roi_camPtr;
typedef boost::shared_ptr< ::yidamsg::Roi_cam const> Roi_camConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::Roi_cam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::Roi_cam_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::Roi_cam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::Roi_cam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::Roi_cam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::Roi_cam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::Roi_cam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::Roi_cam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::Roi_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e9ac17eb247147b3bbfc2b237c971f6";
  }

  static const char* value(const ::yidamsg::Roi_cam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e9ac17eb247147bULL;
  static const uint64_t static_value2 = 0x3bbfc2b237c971f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::Roi_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/Roi_cam";
  }

  static const char* value(const ::yidamsg::Roi_cam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::Roi_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] begin_x\n\
int32[] begin_y\n\
int32[] end_x\n\
int32[] end_y\n\
string task_flag\n\
";
  }

  static const char* value(const ::yidamsg::Roi_cam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::Roi_cam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.begin_x);
      stream.next(m.begin_y);
      stream.next(m.end_x);
      stream.next(m.end_y);
      stream.next(m.task_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Roi_cam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::Roi_cam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::Roi_cam_<ContainerAllocator>& v)
  {
    s << indent << "begin_x[]" << std::endl;
    for (size_t i = 0; i < v.begin_x.size(); ++i)
    {
      s << indent << "  begin_x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.begin_x[i]);
    }
    s << indent << "begin_y[]" << std::endl;
    for (size_t i = 0; i < v.begin_y.size(); ++i)
    {
      s << indent << "  begin_y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.begin_y[i]);
    }
    s << indent << "end_x[]" << std::endl;
    for (size_t i = 0; i < v.end_x.size(); ++i)
    {
      s << indent << "  end_x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.end_x[i]);
    }
    s << indent << "end_y[]" << std::endl;
    for (size_t i = 0; i < v.end_y.size(); ++i)
    {
      s << indent << "  end_y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.end_y[i]);
    }
    s << indent << "task_flag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_ROI_CAM_H
