// Generated by gencpp from file yidamsg/TaskExecuteStatus.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_TASKEXECUTESTATUS_H
#define YIDAMSG_MESSAGE_TASKEXECUTESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct TaskExecuteStatus_
{
  typedef TaskExecuteStatus_<ContainerAllocator> Type;

  TaskExecuteStatus_()
    : task_history_id(0)
    , task_status(0)  {
    }
  TaskExecuteStatus_(const ContainerAllocator& _alloc)
    : task_history_id(0)
    , task_status(0)  {
  (void)_alloc;
    }



   typedef int32_t _task_history_id_type;
  _task_history_id_type task_history_id;

   typedef uint8_t _task_status_type;
  _task_status_type task_status;





  typedef boost::shared_ptr< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TaskExecuteStatus_

typedef ::yidamsg::TaskExecuteStatus_<std::allocator<void> > TaskExecuteStatus;

typedef boost::shared_ptr< ::yidamsg::TaskExecuteStatus > TaskExecuteStatusPtr;
typedef boost::shared_ptr< ::yidamsg::TaskExecuteStatus const> TaskExecuteStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::TaskExecuteStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2293a62523ff50d550bd7b5b6f6302d3";
  }

  static const char* value(const ::yidamsg::TaskExecuteStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2293a62523ff50d5ULL;
  static const uint64_t static_value2 = 0x50bd7b5b6f6302d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/TaskExecuteStatus";
  }

  static const char* value(const ::yidamsg::TaskExecuteStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 task_history_id\n\
uint8 task_status\n\
";
  }

  static const char* value(const ::yidamsg::TaskExecuteStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_history_id);
      stream.next(m.task_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskExecuteStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::TaskExecuteStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::TaskExecuteStatus_<ContainerAllocator>& v)
  {
    s << indent << "task_history_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_history_id);
    s << indent << "task_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_TASKEXECUTESTATUS_H
