// Generated by gencpp from file yidamsg/ultrasound.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_ULTRASOUND_H
#define YIDAMSG_MESSAGE_ULTRASOUND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct ultrasound_
{
  typedef ultrasound_<ContainerAllocator> Type;

  ultrasound_()
    : name()
    , flag(0)  {
    }
  ultrasound_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , flag(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int16_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::yidamsg::ultrasound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::ultrasound_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasound_

typedef ::yidamsg::ultrasound_<std::allocator<void> > ultrasound;

typedef boost::shared_ptr< ::yidamsg::ultrasound > ultrasoundPtr;
typedef boost::shared_ptr< ::yidamsg::ultrasound const> ultrasoundConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::ultrasound_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::ultrasound_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::ultrasound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::ultrasound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::ultrasound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::ultrasound_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::ultrasound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::ultrasound_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::ultrasound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa8685813b62f3b6086d58d33320cb55";
  }

  static const char* value(const ::yidamsg::ultrasound_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa8685813b62f3b6ULL;
  static const uint64_t static_value2 = 0x086d58d33320cb55ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::ultrasound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/ultrasound";
  }

  static const char* value(const ::yidamsg::ultrasound_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::ultrasound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
int16 flag\n\
";
  }

  static const char* value(const ::yidamsg::ultrasound_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::ultrasound_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasound_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::ultrasound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::ultrasound_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "flag: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_ULTRASOUND_H
