// Generated by gencpp from file yidamsg/walle_speech_recognition.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_WALLE_SPEECH_RECOGNITION_H
#define YIDAMSG_MESSAGE_WALLE_SPEECH_RECOGNITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct walle_speech_recognition_
{
  typedef walle_speech_recognition_<ContainerAllocator> Type;

  walle_speech_recognition_()
    : direction(0.0)
    , cmd_id(0)
    , txt()  {
    }
  walle_speech_recognition_(const ContainerAllocator& _alloc)
    : direction(0.0)
    , cmd_id(0)
    , txt(_alloc)  {
  (void)_alloc;
    }



   typedef float _direction_type;
  _direction_type direction;

   typedef int32_t _cmd_id_type;
  _cmd_id_type cmd_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _txt_type;
  _txt_type txt;





  typedef boost::shared_ptr< ::yidamsg::walle_speech_recognition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::walle_speech_recognition_<ContainerAllocator> const> ConstPtr;

}; // struct walle_speech_recognition_

typedef ::yidamsg::walle_speech_recognition_<std::allocator<void> > walle_speech_recognition;

typedef boost::shared_ptr< ::yidamsg::walle_speech_recognition > walle_speech_recognitionPtr;
typedef boost::shared_ptr< ::yidamsg::walle_speech_recognition const> walle_speech_recognitionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::walle_speech_recognition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::walle_speech_recognition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::walle_speech_recognition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::walle_speech_recognition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c1479f10a37544af7437fcac2573154";
  }

  static const char* value(const ::yidamsg::walle_speech_recognition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c1479f10a37544aULL;
  static const uint64_t static_value2 = 0xf7437fcac2573154ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/walle_speech_recognition";
  }

  static const char* value(const ::yidamsg::walle_speech_recognition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 direction\n\
int32 cmd_id\n\
string txt\n\
";
  }

  static const char* value(const ::yidamsg::walle_speech_recognition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.cmd_id);
      stream.next(m.txt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct walle_speech_recognition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::walle_speech_recognition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::walle_speech_recognition_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
    s << indent << "cmd_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd_id);
    s << indent << "txt: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.txt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_WALLE_SPEECH_RECOGNITION_H
