// Generated by gencpp from file yidamsg/walle_audio_broadcase.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_WALLE_AUDIO_BROADCASE_H
#define YIDAMSG_MESSAGE_WALLE_AUDIO_BROADCASE_H

#include <ros/service_traits.h>


#include <yidamsg/walle_audio_broadcaseRequest.h>
#include <yidamsg/walle_audio_broadcaseResponse.h>


namespace yidamsg
{

struct walle_audio_broadcase
{

typedef walle_audio_broadcaseRequest Request;
typedef walle_audio_broadcaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct walle_audio_broadcase
} // namespace yidamsg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yidamsg::walle_audio_broadcase > {
  static const char* value()
  {
    return "c70e73c81cb721a8bec49fb714a48e28";
  }

  static const char* value(const ::yidamsg::walle_audio_broadcase&) { return value(); }
};

template<>
struct DataType< ::yidamsg::walle_audio_broadcase > {
  static const char* value()
  {
    return "yidamsg/walle_audio_broadcase";
  }

  static const char* value(const ::yidamsg::walle_audio_broadcase&) { return value(); }
};


// service_traits::MD5Sum< ::yidamsg::walle_audio_broadcaseRequest> should match 
// service_traits::MD5Sum< ::yidamsg::walle_audio_broadcase > 
template<>
struct MD5Sum< ::yidamsg::walle_audio_broadcaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::walle_audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::walle_audio_broadcaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::walle_audio_broadcaseRequest> should match 
// service_traits::DataType< ::yidamsg::walle_audio_broadcase > 
template<>
struct DataType< ::yidamsg::walle_audio_broadcaseRequest>
{
  static const char* value()
  {
    return DataType< ::yidamsg::walle_audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::walle_audio_broadcaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yidamsg::walle_audio_broadcaseResponse> should match 
// service_traits::MD5Sum< ::yidamsg::walle_audio_broadcase > 
template<>
struct MD5Sum< ::yidamsg::walle_audio_broadcaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::walle_audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::walle_audio_broadcaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::walle_audio_broadcaseResponse> should match 
// service_traits::DataType< ::yidamsg::walle_audio_broadcase > 
template<>
struct DataType< ::yidamsg::walle_audio_broadcaseResponse>
{
  static const char* value()
  {
    return DataType< ::yidamsg::walle_audio_broadcase >::value();
  }
  static const char* value(const ::yidamsg::walle_audio_broadcaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YIDAMSG_MESSAGE_WALLE_AUDIO_BROADCASE_H
