// Generated by gencpp from file yidamsg/walle_play_audio.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_WALLE_PLAY_AUDIO_H
#define YIDAMSG_MESSAGE_WALLE_PLAY_AUDIO_H

#include <ros/service_traits.h>


#include <yidamsg/walle_play_audioRequest.h>
#include <yidamsg/walle_play_audioResponse.h>


namespace yidamsg
{

struct walle_play_audio
{

typedef walle_play_audioRequest Request;
typedef walle_play_audioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct walle_play_audio
} // namespace yidamsg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yidamsg::walle_play_audio > {
  static const char* value()
  {
    return "1b4b6be30129215f962c2b865c54cf1f";
  }

  static const char* value(const ::yidamsg::walle_play_audio&) { return value(); }
};

template<>
struct DataType< ::yidamsg::walle_play_audio > {
  static const char* value()
  {
    return "yidamsg/walle_play_audio";
  }

  static const char* value(const ::yidamsg::walle_play_audio&) { return value(); }
};


// service_traits::MD5Sum< ::yidamsg::walle_play_audioRequest> should match 
// service_traits::MD5Sum< ::yidamsg::walle_play_audio > 
template<>
struct MD5Sum< ::yidamsg::walle_play_audioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::walle_play_audio >::value();
  }
  static const char* value(const ::yidamsg::walle_play_audioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::walle_play_audioRequest> should match 
// service_traits::DataType< ::yidamsg::walle_play_audio > 
template<>
struct DataType< ::yidamsg::walle_play_audioRequest>
{
  static const char* value()
  {
    return DataType< ::yidamsg::walle_play_audio >::value();
  }
  static const char* value(const ::yidamsg::walle_play_audioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yidamsg::walle_play_audioResponse> should match 
// service_traits::MD5Sum< ::yidamsg::walle_play_audio > 
template<>
struct MD5Sum< ::yidamsg::walle_play_audioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yidamsg::walle_play_audio >::value();
  }
  static const char* value(const ::yidamsg::walle_play_audioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yidamsg::walle_play_audioResponse> should match 
// service_traits::DataType< ::yidamsg::walle_play_audio > 
template<>
struct DataType< ::yidamsg::walle_play_audioResponse>
{
  static const char* value()
  {
    return DataType< ::yidamsg::walle_play_audio >::value();
  }
  static const char* value(const ::yidamsg::walle_play_audioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YIDAMSG_MESSAGE_WALLE_PLAY_AUDIO_H
