// Generated by gencpp from file yidamsg/yuntai_preset_control.msg
// DO NOT EDIT!


#ifndef YIDAMSG_MESSAGE_YUNTAI_PRESET_CONTROL_H
#define YIDAMSG_MESSAGE_YUNTAI_PRESET_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yidamsg
{
template <class ContainerAllocator>
struct yuntai_preset_control_
{
  typedef yuntai_preset_control_<ContainerAllocator> Type;

  yuntai_preset_control_()
    : id(0)
    , horizontal(0)
    , vertical(0)
    , focus(0)  {
    }
  yuntai_preset_control_(const ContainerAllocator& _alloc)
    : id(0)
    , horizontal(0)
    , vertical(0)
    , focus(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _horizontal_type;
  _horizontal_type horizontal;

   typedef int32_t _vertical_type;
  _vertical_type vertical;

   typedef int32_t _focus_type;
  _focus_type focus;





  typedef boost::shared_ptr< ::yidamsg::yuntai_preset_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yidamsg::yuntai_preset_control_<ContainerAllocator> const> ConstPtr;

}; // struct yuntai_preset_control_

typedef ::yidamsg::yuntai_preset_control_<std::allocator<void> > yuntai_preset_control;

typedef boost::shared_ptr< ::yidamsg::yuntai_preset_control > yuntai_preset_controlPtr;
typedef boost::shared_ptr< ::yidamsg::yuntai_preset_control const> yuntai_preset_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yidamsg::yuntai_preset_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yidamsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'yidamsg': ['/home/mahxn0/catkin_ws/src/yidamsg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yidamsg::yuntai_preset_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yidamsg::yuntai_preset_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yidamsg::yuntai_preset_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c1b995bdb29e4b1c0fa2508de065fb9";
  }

  static const char* value(const ::yidamsg::yuntai_preset_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c1b995bdb29e4b1ULL;
  static const uint64_t static_value2 = 0xc0fa2508de065fb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yidamsg/yuntai_preset_control";
  }

  static const char* value(const ::yidamsg::yuntai_preset_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int32 horizontal\n\
int32 vertical\n\
int32 focus\n\
";
  }

  static const char* value(const ::yidamsg::yuntai_preset_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.horizontal);
      stream.next(m.vertical);
      stream.next(m.focus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yuntai_preset_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yidamsg::yuntai_preset_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yidamsg::yuntai_preset_control_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "horizontal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.horizontal);
    s << indent << "vertical: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vertical);
    s << indent << "focus: ";
    Printer<int32_t>::stream(s, indent + "  ", v.focus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YIDAMSG_MESSAGE_YUNTAI_PRESET_CONTROL_H
