(cl:in-package yidamsg-msg)
(cl:export '(TASKID-VAL
          TASKID
          START_X-VAL
          START_X
          START_Y-VAL
          START_Y
          START_Z-VAL
          START_Z
          END_X-VAL
          END_X
          END_Y-VAL
          END_Y
          END_Z-VAL
          END_Z
          ALLDIS-VAL
          ALLDIS
          DIS-VAL
          DIS
          SPEED-VAL
          SPEED
          DIS_LEFT-VAL
          DIS_LEFT
          DIS_RIGHT-VAL
          DIS_RIGHT
          NEXT_WIDTH-VAL
          NEXT_WIDTH
          ROAD_WIDTH-VAL
          ROAD_WIDTH
          CONTROL_FLAG-VAL
          CONTROL_FLAG
          LOG-VAL
          LOG
          DIRECTION-VAL
          DIRECTION
          ALIGN-VAL
          ALIGN
))