(cl:in-package yidamsg-msg)
(cl:export '(ID-VAL
          ID
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ANGLEX-VAL
          ANGLEX
          ANGLEY-VAL
          ANGLEY
          ANGLEZ-VAL
          ANGLEZ
          PROB-VAL
          PROB
          X1-VAL
          X1
          Y1-VAL
          Y1
          X2-VAL
          X2
          Y2-VAL
          Y2
          X3-VAL
          X3
          Y3-VAL
          Y3
          X4-VAL
          X4
          Y4-VAL
          Y4
          ROAD_LINE_STATUS-VAL
          ROAD_LINE_STATUS
          ROBOT_ROAD_ANGLE-VAL
          ROBOT_ROAD_ANGLE
          DISTANCE-VAL
          DISTANCE
          TURN_ANGLE-VAL
          TURN_ANGLE
))